import os
from datetime import datetime
from langchain_core.prompts import ChatPromptTemplate
from agents.state import CareerCounselingState, AgentLogEntry
from agents.llm_helper import get_llm

def synthesizer_agent(state: CareerCounselingState) -> CareerCounselingState:
    """
    Synthesizer Agent: Combines all agent findings into a beautiful, empathetic, and comprehensive final report.
    """
    print("--- SYNTHESIZER AGENT STARTING ---")
    
    user_profile = state.get("user_profile")
    career_recs = state.get("career_recommendations")
    skill_gap = state.get("skill_gap_report")
    roadmap = state.get("roadmap_plan")
    scoring = state.get("employability_scoring")
    
    if not all([user_profile, career_recs, skill_gap, roadmap, scoring]):
        raise ValueError("One or more intermediate agent outputs are missing in Synthesizer Agent!")
        
    system_prompt = (
        "You are the Lead Counselor and Synthesizer Agent for SheStarts Career Guide. Your goal is to combine "
        "all the technical reports, roadmaps, and scores generated by your team of specialist agents into a "
        "single, highly polished, empathetic, and professional career restart counselor summary. "
        "Use encouraging, warm, and empowering language. Highlight the candidate's core strengths, validate the "
        "reason for their career break, and give a clear overview of their upcoming upskilling journey."
    )
    
    # We compile the data into a readable format for the LLM
    user_prompt = (
        "Here are the findings from the specialized agents:\n\n"
        "1. Candidate Profile:\n"
        "- Name: {name}\n"
        "- Education: {education}\n"
        "- Gap Duration: {gap_years} years (Reason: {gap_reason})\n"
        "- Current Skills: {current_skills}\n\n"
        "2. Career Recommendations:\n"
        "{career_recommendations_summary}\n\n"
        "3. Skill Gap Analysis (Target: {target_role}):\n"
        "- Matching Skills: {matching_skills}\n"
        "- Missing Skills: {missing_skills}\n\n"
        "4. Upskilling Roadmap Summary:\n"
        "- Phase 1 (30 days) Milestone: {p30_milestone}\n"
        "- Phase 2 (60 days) Milestone: {p60_milestone}\n"
        "- Phase 3 (90 days) Milestone: {p90_milestone}\n\n"
        "5. Employability Score: {overall_score}/100\n"
        "- Experience Score: {exp_score}/100\n"
        "- Skill Relevance Score: {skill_score}/100\n"
        "- Market Demand Score: {demand_score}/100\n"
        "- Time Availability Score: {time_score}/100\n"
        "- Gap Mitigation Score: {gap_score}/100\n"
        "- Feedback: {feedback_summary}\n\n"
        "Write a beautiful counseling report. Use markdown formatting with clear headings, bullet points, and callouts. "
        "Make it look premium, motivating, and immediately actionable."
    )
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("user", user_prompt)
    ])
    
    # Format strings for the prompt
    recs_str = "\n".join([
        f"- {p.title}: Suitability: {p.suitability_reasoning} | Barrier: {p.entry_barrier} | Demand: {p.demand_index_2026}"
        for p in career_recs.recommended_paths
    ])
    
    matching_skills_str = ", ".join(skill_gap.matching_skills)
    missing_skills_str = ", ".join([f"{ms.skill_name} ({ms.importance_level})" for ms in skill_gap.missing_skills])
    
    p30_milestone = roadmap.phase_30_days[0].goal_milestone if roadmap.phase_30_days else "Not specified"
    p60_milestone = roadmap.phase_60_days[0].goal_milestone if roadmap.phase_60_days else "Not specified"
    p90_milestone = roadmap.phase_90_days[0].goal_milestone if roadmap.phase_90_days else "Not specified"
    
    prompt_vars = {
        "name": user_profile.name,
        "education": user_profile.education,
        "gap_years": str(user_profile.gap_duration_years),
        "gap_reason": user_profile.gap_reason,
        "current_skills": ", ".join(user_profile.current_skills),
        "career_recommendations_summary": recs_str,
        "target_role": skill_gap.target_role,
        "matching_skills": matching_skills_str,
        "missing_skills": missing_skills_str,
        "p30_milestone": p30_milestone,
        "p60_milestone": p60_milestone,
        "p90_milestone": p90_milestone,
        "overall_score": str(scoring.overall_score),
        "exp_score": str(scoring.factor_breakdown.experience_score),
        "skill_score": str(scoring.factor_breakdown.skill_relevance_score),
        "demand_score": str(scoring.factor_breakdown.market_demand_score),
        "time_score": str(scoring.factor_breakdown.time_availability_score),
        "gap_score": str(scoring.factor_breakdown.gap_mitigation_score),
        "feedback_summary": scoring.overall_feedback
    }
    
    try:
        # Call standard LLM for generating markdown response
        llm = get_llm(state)
        chain = prompt | llm
        response = chain.invoke(prompt_vars)
        synthesized_response = response.content if hasattr(response, 'content') else str(response)
    except Exception as e:
        print(f"Synthesizer LLM invocation failed: {e}. Generating static backup summary.")
        # Minimal markdown fallback
        synthesized_response = f"""
# Welcome Back to Your Career, {user_profile.name}!

We are absolutely thrilled to assist you in this exciting transition. Taking a break to focus on {user_profile.gap_reason} is a badge of dedication and resilience, and the skills you developed during this period—such as multitasking, project management, and high empathy—are deeply valued in the modern workforce.

### Your Path Forward: **{skill_gap.target_role}**
Based on our multi-agent evaluation, you are highly suited to pivot into this role. Your overall **Employability Restart Index is {scoring.overall_score}/100**, indicating a strong baseline with clear upskilling milestones ahead.

### Next Steps:
1. **Focus on Skills**: Bridge critical gaps in {missing_skills_str} over the next 90 days.
2. **Follow Your Roadmap**: Complete the courses outlined in your 30/60/90-day learning plan.
3. **Build Your Portfolio**: Create practical projects representing your new skills and start applying to returnship programs.

*Remember, every expert was once a beginner. You have what it takes to restart strong!*
"""

    log_entry: AgentLogEntry = {
        "agent_name": "Synthesizer Agent",
        "action": "Compiled and synthesized all counselor recommendations into an empathetic, unified final report.",
        "output_preview": f"Synthesized report generated successfully. Word count: {len(synthesized_response.split())} words.",
        "timestamp": datetime.now().isoformat()
    }
    
    new_state = state.copy()
    new_state["synthesized_response"] = synthesized_response
    new_state["agent_logs"].append(log_entry)
    
    print("--- SYNTHESIZER AGENT COMPLETE ---")
    return new_state
    